"""fixed rel

Revision ID: 48ffa3b1dbad
Revises: fb0d4c14af35
Create Date: 2025-08-18 14:45:51.208321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48ffa3b1dbad'
down_revision: Union[str, None] = 'fb0d4c14af35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
